# Weather forecasts from OpenWeatherMap API

API documentation: https://openweathermap.org/api/forecast5?collection=current_forecast

## Libraries and Constants

In [5]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv

In [6]:
load_dotenv()
connection_string = os.getenv("CON_STRING")
weather_key = os.getenv("WEATHER_KEY")

In [7]:
cities_df = pd.read_sql("cities", con=connection_string)
cities_df

   city_id     name  country  latitude  longitude
0        1   Berlin  Germany     52.52      13.41
1        2  Hamburg  Germany     53.55      10.00
2        3   Munich  Germany     48.14      11.58

## One city, one forecast

Start small by calling the API on a single location and exploring the returned data for one time

In [8]:
# select one row of cities_df
berlin = cities_df.loc[0]

url = "https://api.openweathermap.org/data/2.5/forecast"
params = {"lat": berlin["latitude"], "lon" :berlin["longitude"], "appid":weather_key}

response = requests.get(url, params=params)
response

A response code of `200` means a successful request! Let's start exploring.

In [9]:
# transform output, check keys
response_json = response.json()
response_json.keys()

dict_keys(['cod', 'message', 'cnt', 'list', 'city'])

Let's go through the keys one at time to understand the data structure

In [10]:
# looks like the status code
response_json['cod']

'200'

In [11]:
# ???
response_json['message']

0

In [12]:
# one forecast every 3 hours means 8 per day; five days times 8 makes 40 forecasts
response_json['cnt']

40

In [13]:
# looks like the forecasts themselves
response_json['list']

[{'dt': 1792422000,
  'main': {'temp': 284.75,
   'feels_like': 283.56,
   'temp_min': 284,
   'temp_max': 284.75,
   'pressure': 1031,
   'sea_level': 1031,
   'grnd_level': 1025,
   'humidity': 61,
   'temp_kf': 0.75,
   'dew_point': 277.49},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 21},
  'wind': {'speed': 2.73, 'deg': 58, 'gust': 5.83},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-19 15:00:00'},
 {'dt': 1792432800,
  'main': {'temp': 282.12,
   'feels_like': 280.9,
   'temp_min': 280.62,
   'temp_max': 282.12,
   'pressure': 1030,
   'sea_level': 1030,
   'grnd_level': 1025,
   'humidity': 72,
   'temp_kf': 1.5,
   'dew_point': 277.35},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 27},
  'wind': {'speed': 2.3, 'deg': 61, 'gust': 4.43},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-19 18:00:00'},
 {'dt': 1792443600,
  'main': {'temp': 281.52,
   'feels_like': 280.4,
   'temp_min': 281.52,
   'temp_max': 281.52,
   'pressure': 1029,
   'sea_level': 1029,
   'grnd_level': 1024,
   'humidity': 78,
   'temp_kf': 0,
   'dew_point': 276.84},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 96},
  'wind': {'speed': 2.05, 'deg': 76, 'gust': 4.12},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-19 21:00:00'},
 {'dt': 1792454400,
  'main': {'temp': 280.99,
   'feels_like': 279.36,
   'temp_min': 280.99,
   'temp_max': 280.99,
   'pressure': 1028,
   'sea_level': 1028,
   'grnd_level': 1023,
   'humidity': 84,
   'temp_kf': 0,
   'dew_point': 276.32},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 97},
  'wind': {'speed': 2.58, 'deg': 83, 'gust': 5.06},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-20 00:00:00'},
 {'dt': 1792465200,
  'main': {'temp': 280.06,
   'feels_like': 278.12,
   'temp_min': 280.06,
   'temp_max': 280.06,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1020,
   'humidity': 92,
   'temp_kf': 0,
   'dew_point': 276.61},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 80},
  'wind': {'speed': 2.75, 'deg': 75, 'gust': 5.39},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-20 03:00:00'},
 {'dt': 1792476000,
  'main': {'temp': 279.37,
   'feels_like': 277.46,
   'temp_min': 279.37,
   'temp_max': 279.37,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 94,
   'temp_kf': 0,
   'dew_point': 276.37},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 98},
  'wind': {'speed': 2.54, 'deg': 77, 'gust': 5.01},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-20 06:00:00'},
 {'dt': 1792486800,
  'main': {'temp': 282.23,
   'feels_like': 280.39,
   'temp_min': 282.23,
   'temp_max': 282.23,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1017,
   'humidity': 83,
   'temp_kf': 0,
   'dew_point': 277.73},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.29, 'deg': 84, 'gust': 7.7},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-20 09:00:00'},
 {'dt': 1792497600,
  'main': {'temp': 283.77,
   'feels_like': 282.79,
   'temp_min': 283.77,
   'temp_max': 283.77,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1014,
   'humidity': 73,
   'temp_kf': 0,
   'dew_point': 278.16},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.32, 'deg': 96, 'gust': 7.41},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-20 12:00:00'},
 {'dt': 1792508400,
  'main': {'temp': 284.12,
   'feels_like': 283.18,
   'temp_min': 284.12,
   'temp_max': 284.12,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 1012,
   'humidity': 73,
   'temp_kf': 0,
   'dew_point': 278.53},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.64, 'deg': 101, 'gust': 5.56},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-20 15:00:00'},
 {'dt': 1792519200,
  'main': {'temp': 283.15,
   'feels_like': 281.84,
   'temp_min': 283.15,
   'temp_max': 283.15,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1010,
   'humidity': 77,
   'temp_kf': 0,
   'dew_point': 278.8},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.71, 'deg': 90, 'gust': 5.52},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-20 18:00:00'},
 {'dt': 1792530000,
  'main': {'temp': 282.71,
   'feels_like': 281.4,
   'temp_min': 282.71,
   'temp_max': 282.71,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 83,
   'temp_kf': 0,
   'dew_point': 279.63},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.57, 'deg': 103, 'gust': 4.98},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-20 21:00:00'},
 {'dt': 1792540800,
  'main': {'temp': 282.77,
   'feels_like': 281.35,
   'temp_min': 282.77,
   'temp_max': 282.77,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1006,
   'humidity': 86,
   'temp_kf': 0,
   'dew_point': 280.27},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.77, 'deg': 122, 'gust': 5.43},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-21 00:00:00'},
 {'dt': 1792551600,
  'main': {'temp': 282.9,
   'feels_like': 281.48,
   'temp_min': 282.9,
   'temp_max': 282.9,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1005,
   'humidity': 88,
   'temp_kf': 0,
   'dew_point': 280.92},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.8, 'deg': 126, 'gust': 5.5},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-21 03:00:00'},
 {'dt': 1792562400,
  'main': {'temp': 282.92,
   'feels_like': 281.62,
   'temp_min': 282.92,
   'temp_max': 282.92,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1004,
   'humidity': 87,
   'temp_kf': 0,
   'dew_point': 280.9},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 73},
  'wind': {'speed': 2.62, 'deg': 121, 'gust': 5.14},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-21 06:00:00'},
 {'dt': 1792573200,
  'main': {'temp': 284.58,
   'feels_like': 283.92,
   'temp_min': 284.58,
   'temp_max': 284.58,
   'pressure': 1009,
   'sea_level': 1009,
   'grnd_level': 1004,
   'humidity': 82,
   'temp_kf': 0,
   'dew_point': 281.61},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 95},
  'wind': {'speed': 2.84, 'deg': 124, 'gust': 6.04},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-21 09:00:00'},
 {'dt': 1792584000,
  'main': {'temp': 287.32,
   'feels_like': 286.75,
   'temp_min': 287.32,
   'temp_max': 287.32,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 1003,
   'humidity': 75,
   'temp_kf': 0,
   'dew_point': 282.86},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 89},
  'wind': {'speed': 1.57, 'deg': 120, 'gust': 4.13},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-21 12:00:00'},
 {'dt': 1792594800,
  'main': {'temp': 287.83,
   'feels_like': 287.49,
   'temp_min': 287.83,
   'temp_max': 287.83,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 1003,
   'humidity': 82,
   'temp_kf': 0,
   'dew_point': 284.76},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 0.68, 'deg': 177, 'gust': 0.94},
  'visibility': 10000,
  'pop': 0.21,
  'rain': {'3h': 0.25},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-21 15:00:00'},
 {'dt': 1792605600,
  'main': {'temp': 285.23,
   'feels_like': 284.95,
   'temp_min': 285.23,
   'temp_max': 285.23,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 1003,
   'humidity': 94,
   'temp_kf': 0,
   'dew_point': 284.25},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.32, 'deg': 230, 'gust': 4.26},
  'visibility': 6788,
  'pop': 1,
  'rain': {'3h': 0.79},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-21 18:00:00'},
 {'dt': 1792616400,
  'main': {'temp': 283.93,
   'feels_like': 283.62,
   'temp_min': 283.93,
   'temp_max': 283.93,
   'pressure': 1009,
   'sea_level': 1009,
   'grnd_level': 1003,
   'humidity': 98,
   'temp_kf': 0,
   'dew_point': 283.54},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.7, 'deg': 236, 'gust': 5.19},
  'visibility': 4475,
  'pop': 1,
  'rain': {'3h': 0.93},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-21 21:00:00'},
 {'dt': 1792627200,
  'main': {'temp': 283.59,
   'feels_like': 283.2,
   'temp_min': 283.59,
   'temp_max': 283.59,
   'pressure': 1009,
   'sea_level': 1009,
   'grnd_level': 1004,
   'humidity': 96,
   'temp_kf': 0,
   'dew_point': 282.98},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.02, 'deg': 263, 'gust': 7.74},
  'visibility': 4922,
  'pop': 1,
  'rain': {'3h': 2.3},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-22 00:00:00'},
 {'dt': 1792638000,
  'main': {'temp': 283.14,
   'feels_like': 281.39,
   'temp_min': 283.14,
   'temp_max': 283.14,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1005,
   'humidity': 97,
   'temp_kf': 0,
   'dew_point': 282.63},
  'weather': [{'id': 501,
    'main': 'Rain',
    'description': 'moderate rain',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.47, 'deg': 245, 'gust': 6.64},
  'visibility': 2795,
  'pop': 1,
  'rain': {'3h': 4.12},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-22 03:00:00'},
 {'dt': 1792648800,
  'main': {'temp': 282.58,
   'feels_like': 280.52,
   'temp_min': 282.58,
   'temp_max': 282.58,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1006,
   'humidity': 96,
   'temp_kf': 0,
   'dew_point': 281.93},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.85, 'deg': 257, 'gust': 7.51},
  'visibility': 5698,
  'pop': 1,
  'rain': {'3h': 2.87},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-22 06:00:00'},
 {'dt': 1792659600,
  'main': {'temp': 283.3,
   'feels_like': 282.49,
   'temp_min': 283.3,
   'temp_max': 283.3,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1007,
   'humidity': 81,
   'temp_kf': 0,
   'dew_point': 280.21},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.25, 'deg': 252, 'gust': 9.61},
  'visibility': 10000,
  'pop': 0.2,
  'rain': {'3h': 0.14},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-22 09:00:00'},
 {'dt': 1792670400,
  'main': {'temp': 284.64,
   'feels_like': 283.54,
   'temp_min': 284.64,
   'temp_max': 284.64,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1007,
   'humidity': 65,
   'temp_kf': 0,
   'dew_point': 278.2},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.55, 'deg': 245, 'gust': 10.16},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-22 12:00:00'},
 {'dt': 1792681200,
  'main': {'temp': 284.74,
   'feels_like': 283.65,
   'temp_min': 284.74,
   'temp_max': 284.74,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1007,
   'humidity': 65,
   'temp_kf': 0,
   'dew_point': 278.29},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 42},
  'wind': {'speed': 2.93, 'deg': 214, 'gust': 6.14},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-22 15:00:00'},
 {'dt': 1792692000,
  'main': {'temp': 283.82,
   'feels_like': 282.74,
   'temp_min': 283.82,
   'temp_max': 283.82,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 69,
   'temp_kf': 0,
   'dew_point': 278.44},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 99},
  'wind': {'speed': 2.91, 'deg': 210, 'gust': 6.02},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-22 18:00:00'},
 {'dt': 1792702800,
  'main': {'temp': 283.21,
   'feels_like': 282.31,
   'temp_min': 283.21,
   'temp_max': 283.21,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 78,
   'temp_kf': 0,
   'dew_point': 279.54},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 99},
  'wind': {'speed': 3.52, 'deg': 207, 'gust': 7.15},
  'visibility': 5326,
  'pop': 0.97,
  'rain': {'3h': 0.18},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-22 21:00:00'},
 {'dt': 1792713600,
  'main': {'temp': 281.58,
   'feels_like': 279.56,
   'temp_min': 281.58,
   'temp_max': 281.58,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 92,
   'temp_kf': 0,
   'dew_point': 280.37},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 30},
  'wind': {'speed': 3.37, 'deg': 205, 'gust': 6.59},
  'visibility': 10000,
  'pop': 0.2,
  'rain': {'3h': 0.57},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-23 00:00:00'},
 {'dt': 1792724400,
  'main': {'temp': 280.32,
   'feels_like': 278.53,
   'temp_min': 280.32,
   'temp_max': 280.32,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1007,
   'humidity': 96,
   'temp_kf': 0,
   'dew_point': 279.69},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 14},
  'wind': {'speed': 2.62, 'deg': 191, 'gust': 4.97},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-23 03:00:00'},
 {'dt': 1792735200,
  'main': {'temp': 280.09,
   'feels_like': 278.13,
   'temp_min': 280.09,
   'temp_max': 280.09,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1006,
   'humidity': 97,
   'temp_kf': 0,
   'dew_point': 279.54},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.79, 'deg': 158, 'gust': 5.28},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-23 06:00:00'},
 {'dt': 1792746000,
  'main': {'temp': 281.98,
   'feels_like': 280.11,
   'temp_min': 281.98,
   'temp_max': 281.98,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1005,
   'humidity': 94,
   'temp_kf': 0,
   'dew_point': 281},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.25, 'deg': 136, 'gust': 6.7},
  'visibility': 10000,
  'pop': 0.2,
  'rain': {'3h': 0.12},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-23 09:00:00'},
 {'dt': 1792756800,
  'main': {'temp': 284.05,
   'feels_like': 283.39,
   'temp_min': 284.05,
   'temp_max': 284.05,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 1003,
   'humidity': 84,
   'temp_kf': 0,
   'dew_point': 281.51},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.02, 'deg': 148, 'gust': 8.02},
  'visibility': 10000,
  'pop': 0.2,
  'rain': {'3h': 0.75},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-23 12:00:00'},
 {'dt': 1792767600,
  'main': {'temp': 285.37,
   'feels_like': 284.42,
   'temp_min': 285.37,
   'temp_max': 285.37,
   'pressure': 1006,
   'sea_level': 1006,
   'grnd_level': 1000,
   'humidity': 68,
   'temp_kf': 0,
   'dew_point': 279.61},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.88, 'deg': 134, 'gust': 7.92},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-23 15:00:00'},
 {'dt': 1792778400,
  'main': {'temp': 284.89,
   'feels_like': 283.79,
   'temp_min': 284.89,
   'temp_max': 284.89,
   'pressure': 1003,
   'sea_level': 1003,
   'grnd_level': 998,
   'humidity': 64,
   'temp_kf': 0,
   'dew_point': 278.39},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 28},
  'wind': {'speed': 5.47, 'deg': 138, 'gust': 11.25},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-23 18:00:00'},
 {'dt': 1792789200,
  'main': {'temp': 284.68,
   'feels_like': 283.46,
   'temp_min': 284.68,
   'temp_max': 284.68,
   'pressure': 1002,
   'sea_level': 1002,
   'grnd_level': 997,
   'humidity': 60,
   'temp_kf': 0,
   'dew_point': 277.23},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 78},
  'wind': {'speed': 5.47, 'deg': 150, 'gust': 11.4},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-23 21:00:00'},
 {'dt': 1792800000,
  'main': {'temp': 284.1,
   'feels_like': 283.13,
   'temp_min': 284.1,
   'temp_max': 284.1,
   'pressure': 1000,
   'sea_level': 1000,
   'grnd_level': 995,
   'humidity': 72,
   'temp_kf': 0,
   'dew_point': 279.26},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 5.55, 'deg': 182, 'gust': 11.78},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-24 00:00:00'},
 {'dt': 1792810800,
  'main': {'temp': 281.62,
   'feels_like': 278.28,
   'temp_min': 281.62,
   'temp_max': 281.62,
   'pressure': 1001,
   'sea_level': 1001,
   'grnd_level': 996,
   'humidity': 76,
   'temp_kf': 0,
   'dew_point': 277.69},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 6.51, 'deg': 209, 'gust': 13.96},
  'visibility': 10000,
  'pop': 0.24,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-24 03:00:00'},
 {'dt': 1792821600,
  'main': {'temp': 279.57,
   'feels_like': 275.48,
   'temp_min': 279.57,
   'temp_max': 279.57,
   'pressure': 1003,
   'sea_level': 1003,
   'grnd_level': 998,
   'humidity': 94,
   'temp_kf': 0,
   'dew_point': 278.59},
  'weather': [{'id': 501,
    'main': 'Rain',
    'description': 'moderate rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 7.03, 'deg': 210, 'gust': 13.93},

In [14]:
# matches 'cnt' above!
len(response_json['list'])

40

In [15]:
# we have this info in the 'cities' table
response_json['city']

{'id': 6545310,
 'name': 'Mitte',
 'coord': {'lat': 52.52, 'lon': 13.41},
 'country': 'DE',
 'population': 329078,
 'timezone': 7200,
 'sunrise': 1792388300,
 'sunset': 1792425844}

Time to explore one forecast and see what to keep.

In [16]:
forecast = response_json['list'][0]
forecast

{'dt': 1792422000,
 'main': {'temp': 284.75,
  'feels_like': 283.56,
  'temp_min': 284,
  'temp_max': 284.75,
  'pressure': 1031,
  'sea_level': 1031,
  'grnd_level': 1025,
  'humidity': 61,
  'temp_kf': 0.75,
  'dew_point': 277.49},
 'weather': [{'id': 801,
   'main': 'Clouds',
   'description': 'few clouds',
   'icon': '02d'}],
 'clouds': {'all': 21},
 'wind': {'speed': 2.73, 'deg': 58, 'gust': 5.83},
 'visibility': 10000,
 'pop': 0,
 'sys': {'pod': 'd'},
 'dt_txt': '2026-10-19 15:00:00'}

* dt looks like some kind of timestamp
* main
    * temp looks crazy! 292 degrees!  (use units=metric instead)
    * feels_like might be more important for people than the actual temperature
    * temp_min/max might be worth keeping? maybe not
    * humidity might affect if people rent scooters or not
* weather looks like the kind of descriptions a weather app would show
* clouds probably not needed
* wind
    * speed or gust could be important
* visibility probably not needed
* pop 'probability of precipitation' seems useful
* rain and snow seem useful
* sys probably not needed
* dt_txt a much better timestamp

In [17]:
forecast['wind']#["feels_like"]

{'speed': 2.73, 'deg': 58, 'gust': 5.83}

In [18]:
forecast_data = {
    "temp": forecast['main']['temp'],
    "feels_like": forecast['main']['feels_like'],
    "humidity_%": forecast['main']['humidity'],
    "wind_speed": forecast['wind']['speed'],
    "wind_gust": forecast['wind']['gust'],
    "precipitation_%": forecast['pop'],
    # # docs say there's 'rain' and 'snow', but it's not here!
    "forecast_time": forecast['dt_txt']
}
forecast_data

{'temp': 284.75,
 'feels_like': 283.56,
 'humidity_%': 61,
 'wind_speed': 2.73,
 'wind_gust': 5.83,
 'precipitation_%': 0,
 'forecast_time': '2026-10-19 15:00:00'}

## One city, all forecasts

Now that we have useful information from one forecast, let's try to extract the same information from the other 39, too.

In [19]:
forecasts = []
for forecast in response_json['list']:
    forecast_data = {
        "temp": forecast['main']['temp'],
        "feels_like": forecast['main']['feels_like'],
        "humidity_%": forecast['main']['humidity'],
        "wind_speed": forecast['wind']['speed'],
        "wind_gust": forecast['wind']['gust'],
        "precipitation_%": forecast['pop'],
        "rain_3h": forecast['rain']['3h'],
        # docs say there's 'snow', but it's not here!
        "forecast_time": forecast['dt_txt']
    }
    forecasts.append(forecast_data)
forecasts

KeyError: 'rain'

Oh no! One of the forecasts has no 'rain'!

In [20]:
forecast # the iteration variable stays stuck wherever the loop broke

{'dt': 1792422000,
 'main': {'temp': 284.75,
  'feels_like': 283.56,
  'temp_min': 284,
  'temp_max': 284.75,
  'pressure': 1031,
  'sea_level': 1031,
  'grnd_level': 1025,
  'humidity': 61,
  'temp_kf': 0.75,
  'dew_point': 277.49},
 'weather': [{'id': 801,
   'main': 'Clouds',
   'description': 'few clouds',
   'icon': '02d'}],
 'clouds': {'all': 21},
 'wind': {'speed': 2.73, 'deg': 58, 'gust': 5.83},
 'visibility': 10000,
 'pop': 0,
 'sys': {'pod': 'd'},
 'dt_txt': '2026-10-19 15:00:00'}

Indeed, there's no 'rain' in this dictionary, just like we saw no 'snow' before. JSON documents are semi-structured; where there's no data, they might leave things out rather than listing a null value. Thankfully, python dictionaries have a method that allow us to retrieve a key that might not be there: `.get()`. We can even set the value to return if the key isn't found.

In [21]:
forecast.get('dt_txt')

'2026-10-19 15:00:00'

In [22]:
forecast.get('rain', {}) # {} is the default value

{}

By returning an empty dictionary as the default, we can chain more searches together.

In [23]:
# returns a reasonable value for "no rain in the last three hours"
forecast.get('rain', {}).get('3h', 0)

0

In [24]:
# works just fine if there has been rain
response_json['list'][11].get('rain', {}).get('3h', 0)

0

We'll adjust our loop to use `.get()`

In [25]:
forecasts = []
for forecast in response_json['list']:
    forecast_data = {
        "temp": forecast['main']['temp'],
        "feels_like": forecast['main']['feels_like'],
        "humidity_%": forecast['main']['humidity'],
        "wind_speed": forecast['wind']['speed'],
        "wind_gust": forecast['wind']['gust'],
        "precipitation_%": forecast['pop'],
        "rain_3h": forecast.get('rain', {}).get('3h', 0),
        "snow_3h": forecast.get('snow', {}).get('3h', 0),
        "forecast_time": forecast['dt_txt']
    }
    forecasts.append(forecast_data)
forecasts

[{'temp': 284.75,
  'feels_like': 283.56,
  'humidity_%': 61,
  'wind_speed': 2.73,
  'wind_gust': 5.83,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-19 15:00:00'},
 {'temp': 282.12,
  'feels_like': 280.9,
  'humidity_%': 72,
  'wind_speed': 2.3,
  'wind_gust': 4.43,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-19 18:00:00'},
 {'temp': 281.52,
  'feels_like': 280.4,
  'humidity_%': 78,
  'wind_speed': 2.05,
  'wind_gust': 4.12,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-19 21:00:00'},
 {'temp': 280.99,
  'feels_like': 279.36,
  'humidity_%': 84,
  'wind_speed': 2.58,
  'wind_gust': 5.06,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-20 00:00:00'},
 {'temp': 280.06,
  'feels_like': 278.12,
  'humidity_%': 92,
  'wind_speed': 2.75,
  'wind_gust': 5.39,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-20 03:00:00'},
 {'temp': 279.37,
  'feels_like': 277.46,
  'humidity_%': 94,
  'wind_speed': 2.54,
  'wind_gust': 5.01,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-20 06:00:00'},
 {'temp': 282.23,
  'feels_like': 280.39,
  'humidity_%': 83,
  'wind_speed': 3.29,
  'wind_gust': 7.7,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-20 09:00:00'},
 {'temp': 283.77,
  'feels_like': 282.79,
  'humidity_%': 73,
  'wind_speed': 3.32,
  'wind_gust': 7.41,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-20 12:00:00'},
 {'temp': 284.12,
  'feels_like': 283.18,
  'humidity_%': 73,
  'wind_speed': 2.64,
  'wind_gust': 5.56,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-20 15:00:00'},
 {'temp': 283.15,
  'feels_like': 281.84,
  'humidity_%': 77,
  'wind_speed': 2.71,
  'wind_gust': 5.52,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-20 18:00:00'},
 {'temp': 282.71,
  'feels_like': 281.4,
  'humidity_%': 83,
  'wind_speed': 2.57,
  'wind_gust': 4.98,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-20 21:00:00'},
 {'temp': 282.77,
  'feels_like': 281.35,
  'humidity_%': 86,
  'wind_speed': 2.77,
  'wind_gust': 5.43,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-21 00:00:00'},
 {'temp': 282.9,
  'feels_like': 281.48,
  'humidity_%': 88,
  'wind_speed': 2.8,
  'wind_gust': 5.5,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-21 03:00:00'},
 {'temp': 282.92,
  'feels_like': 281.62,
  'humidity_%': 87,
  'wind_speed': 2.62,
  'wind_gust': 5.14,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-21 06:00:00'},
 {'temp': 284.58,
  'feels_like': 283.92,
  'humidity_%': 82,
  'wind_speed': 2.84,
  'wind_gust': 6.04,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-21 09:00:00'},
 {'temp': 287.32,
  'feels_like': 286.75,
  'humidity_%': 75,
  'wind_speed': 1.57,
  'wind_gust': 4.13,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-21 12:00:00'},
 {'temp': 287.83,
  'feels_like': 287.49,
  'humidity_%': 82,
  'wind_speed': 0.68,
  'wind_gust': 0.94,
  'precipitation_%': 0.21,
  'rain_3h': 0.25,
  'snow_3h': 0,
  'forecast_time': '2026-10-21 15:00:00'},
 {'temp': 285.23,
  'feels_like': 284.95,
  'humidity_%': 94,
  'wind_speed': 2.32,
  'wind_gust': 4.26,
  'precipitation_%': 1,
  'rain_3h': 0.79,
  'snow_3h': 0,
  'forecast_time': '2026-10-21 18:00:00'},
 {'temp': 283.93,
  'feels_like': 283.62,
  'humidity_%': 98,
  'wind_speed': 2.7,
  'wind_gust': 5.19,
  'precipitation_%': 1,
  'rain_3h': 0.93,
  'snow_3h': 0,
  'forecast_time': '2026-10-21 21:00:00'},
 {'temp': 283.59,
  'feels_like': 283.2,
  'humidity_%': 96,
  'wind_speed': 4.02,
  'wind_gust': 7.74,
  'precipitation_%': 1,
  'rain_3h': 2.3,
  'snow_3h': 0,
  'forecast_time': '2026-10-22 00:00:00'},
 {'temp': 283.14,
  'feels_like': 281.39,
  'humidity_%': 97,
  'wind_speed': 3.47,
  'wind_gust': 6.64,
  'precipitation_%': 1,
  'rain_3h': 4.12,
  'snow_3h': 0,
  'forecast_time': '2026-10-22 03:00:00'},
 {'temp': 282.58,
  'feels_like': 280.52,
  'humidity_%': 96,
  'wind_speed': 3.85,
  'wind_gust': 7.51,
  'precipitation_%': 1,
  'rain_3h': 2.87,
  'snow_3h': 0,
  'forecast_time': '2026-10-22 06:00:00'},
 {'temp': 283.3,
  'feels_like': 282.49,
  'humidity_%': 81,
  'wind_speed': 4.25,
  'wind_gust': 9.61,
  'precipitation_%': 0.2,
  'rain_3h': 0.14,
  'snow_3h': 0,
  'forecast_time': '2026-10-22 09:00:00'},
 {'temp': 284.64,
  'feels_like': 283.54,
  'humidity_%': 65,
  'wind_speed': 4.55,
  'wind_gust': 10.16,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-22 12:00:00'},
 {'temp': 284.74,
  'feels_like': 283.65,
  'humidity_%': 65,
  'wind_speed': 2.93,
  'wind_gust': 6.14,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-22 15:00:00'},
 {'temp': 283.82,
  'feels_like': 282.74,
  'humidity_%': 69,
  'wind_speed': 2.91,
  'wind_gust': 6.02,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-22 18:00:00'},
 {'temp': 283.21,
  'feels_like': 282.31,
  'humidity_%': 78,
  'wind_speed': 3.52,
  'wind_gust': 7.15,
  'precipitation_%': 0.97,
  'rain_3h': 0.18,
  'snow_3h': 0,
  'forecast_time': '2026-10-22 21:00:00'},
 {'temp': 281.58,
  'feels_like': 279.56,
  'humidity_%': 92,
  'wind_speed': 3.37,
  'wind_gust': 6.59,
  'precipitation_%': 0.2,
  'rain_3h': 0.57,
  'snow_3h': 0,
  'forecast_time': '2026-10-23 00:00:00'},
 {'temp': 280.32,
  'feels_like': 278.53,
  'humidity_%': 96,
  'wind_speed': 2.62,
  'wind_gust': 4.97,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-23 03:00:00'},
 {'temp': 280.09,
  'feels_like': 278.13,
  'humidity_%': 97,
  'wind_speed': 2.79,
  'wind_gust': 5.28,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-23 06:00:00'},
 {'temp': 281.98,
  'feels_like': 280.11,
  'humidity_%': 94,
  'wind_speed': 3.25,
  'wind_gust': 6.7,
  'precipitation_%': 0.2,
  'rain_3h': 0.12,
  'snow_3h': 0,
  'forecast_time': '2026-10-23 09:00:00'},
 {'temp': 284.05,
  'feels_like': 283.39,
  'humidity_%': 84,
  'wind_speed': 4.02,
  'wind_gust': 8.02,
  'precipitation_%': 0.2,
  'rain_3h': 0.75,
  'snow_3h': 0,
  'forecast_time': '2026-10-23 12:00:00'},
 {'temp': 285.37,
  'feels_like': 284.42,
  'humidity_%': 68,
  'wind_speed': 3.88,
  'wind_gust': 7.92,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-23 15:00:00'},
 {'temp': 284.89,
  'feels_like': 283.79,
  'humidity_%': 64,
  'wind_speed': 5.47,
  'wind_gust': 11.25,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-23 18:00:00'},
 {'temp': 284.68,
  'feels_like': 283.46,
  'humidity_%': 60,
  'wind_speed': 5.47,
  'wind_gust': 11.4,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-23 21:00:00'},
 {'temp': 284.1,
  'feels_like': 283.13,
  'humidity_%': 72,
  'wind_speed': 5.55,
  'wind_gust': 11.78,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-24 00:00:00'},
 {'temp': 281.62,
  'feels_like': 278.28,
  'humidity_%': 76,
  'wind_speed': 6.51,
  'wind_gust': 13.96,
  'precipitation_%': 0.24,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-24 03:00:00'},
 {'temp': 279.57,
  'feels_like': 275.48,
  'humidity_%': 94,
  'wind_speed': 7.03,
  'wind_gust': 13.93,
  'precipitation_%': 1,
  'rain_3h': 5.7,
  'snow_3h': 0,
  'forecast_time': '2026-10-24 06:00:00'},
 {'temp': 281.41,
  'feels_like': 278.27,
  'humidity_%': 87,
  'wind_speed': 5.76,
  'wind_gust': 12.25,
  'precipitation_%': 0.2,
  'rain_3h': 3.51,
  'snow_3h': 0,
  'forecast_time': '2026-10-24 09:00:00'},
 {'temp': 283.7,
  'feels_like': 282.53,
  'humidity_%': 66,
  'wind_speed': 5.79,
  'wind_gust': 12.62,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-10-24 12:00:00'}]

In [26]:
pd.DataFrame(forecasts)

,temp,feels_like,humidity_%,wind_speed,wind_gust,precipitation_%,rain_3h,snow_3h,forecast_time
0,284.75,283.56,61,2.73,5.83,0.00,0.00,0,2026-10-19 15:00:00
1,282.12,280.90,72,2.30,4.43,0.00,0.00,0,2026-10-19 18:00:00
2,281.52,280.40,78,2.05,4.12,0.00,0.00,0,2026-10-19 21:00:00
3,280.99,279.36,84,2.58,5.06,0.00,0.00,0,2026-10-20 00:00:00
4,280.06,278.12,92,2.75,5.39,0.00,0.00,0,2026-10-20 03:00:00
5,279.37,277.46,94,2.54,5.01,0.00,0.00,0,2026-10-20 06:00:00
6,282.23,280.39,83,3.29,7.70,0.00,0.00,0,2026-10-20 09:00:00
7,283.77,282.79,73,3.32,7.41,0.00,0.00,0,2026-10-20 12:00:00
8,284.12,283.18,73,2.64,5.56,0.00,0.00,0,2026-10-20 15:00:00
9,283.15,281.84,77,2.71,5.52,0.00,0.00,0,2026-10-20 18:00:00
10,282.71,281.40,83,2.57,4.98,0.00,0.00,0,2026-10-20 21:00:00
11,282.77,281.35,86,2.77,5.43,0.00,0.00,0,2026-10-21 00:00:00
12,282.90,281.48,88,2.80,5.50,0.00,0.00,0,2026-10-21 03:00:00
13,282.92,281.62,87,2.62,5.14,0.00,0.00,0,2026-10-21 06:00:00
14,284.58,283.92,82,2.84,6.04,0.00,0.00,0,2026-10-21 09:00:00
15,287.32,286.75,75,1.57,4.13,0.00,0.00,0,2026-10-21 12:00:00
16,287.83,287.49,82,0.68,0.94,0.21,0.25,0,2026-10-21 15:00:00
17,285.23,284.95,94,2.32,4.26,1.00,0.79,0,2026-10-21 18:00:00
18,283.93,283.62,98,2.70,5.19,1.00,0.93,0,2026-10-21 21:00:00
19,283.59,283.20,96,4.02,7.74,1.00,2.30,0,2026-10-22 00:00:00
20,283.14,281.39,97,3.47,6.64,1.00,4.12,0,2026-10-22 03:00:00
21,282.58,280.52,96,3.85,7.51,1.00,2.87,0,2026-10-22 06:00:00
22,283.30,282.49,81,4.25,9.61,0.20,0.14,0,2026-10-22 09:00:00
23,284.64,283.54,65,4.55,10.16,0.00,0.00,0,2026-10-22 12:00:00
24,284.74,283.65,65,2.93,6.14,0.00,0.00,0,2026-10-22 15:00:00
25,283.82,282.74,69,2.91,6.02,0.00,0.00,0,2026-10-22 18:00:00
26,283.21,282.31,78,3.52,7.15,0.97,0.18,0,2026-10-22 21:00:00
27,281.58,279.56,92,3.37,6.59,0.20,0.57,0,2026-10-23 00:00:00
28,280.32,278.53,96,2.62,4.97,0.00,0.00,0,2026-10-23 03:00:00
29,280.09,278.13,97,2.79,5.28,0.00,0.00,0,2026-10-23 06:00:00
30,281.98,280.11,94,3.25,6.70,0.20,0.12,0,2026-10-23 09:00:00
31,284.05,283.39,84,4.02,8.02,0.20,0.75,0,2026-10-23 12:00:00
32,285.37,284.42,68,3.88,7.92,0.00,0.00,0,2026-10-23 15:00:00
33,284.89,283.79,64,5.47,11.25,0.00,0.00,0,2026-10-23 18:00:00
34,284.68,283.46,60,5.47,11.40,0.00,0.00,0,2026-10-23 21:00:00
35,284.10,283.13,72,5.55,11.78,0.00,0.00,0,2026-10-24 00:00:00
36,281.62,278.28,76,6.51,13.96,0.24,0.00,0,2026-10-24 03:00:00
37,279.57,275.48,94,7.03,13.93,1.00,5.70,0,2026-10-24 06:00:00
38,281.41,278.27,87,5.76,12.25,0.20,3.51,0,2026-10-24 09:00:00
39,283.70,282.53,66,5.79,12.62,0.00,0.00,0,2026-10-24 12:00:00

## All cities, all forecasts

Now let's expand one more time by adding a loop to handle each of our three cities.

In [27]:
cities_df

   city_id     name  country  latitude  longitude
0        1   Berlin  Germany     52.52      13.41
1        2  Hamburg  Germany     53.55      10.00
2        3   Munich  Germany     48.14      11.58

In [28]:
forecasts = []
url = "https://api.openweathermap.org/data/2.5/forecast"

# loop through cities_dfa
for _, row in cities_df.iterrows():
    # don't forget to add a parameter to use metric units!
    params = {"lat": row["latitude"], "lon" :row["longitude"], "appid":weather_key, "units": "metric"}
    response = requests.get(url, params=params)
    response_json = response.json()
    
    for forecast in response_json['list']:
        forecast_data = {
            "temp": forecast['main']['temp'],
            "feels_like": forecast['main']['feels_like'],
            "humidity_%": forecast['main']['humidity'],
            "wind_speed": forecast['wind']['speed'],
            "wind_gust": forecast['wind']['gust'],
            "precipitation_%": forecast['pop'],
            "rain_3h": forecast.get('rain', {}).get('3h', 0),
            "snow_3h": forecast.get('snow', {}).get('3h', 0),
            "forecast_time": forecast['dt_txt'],
            "city_id": row["city_id"] # add city_id to reference back to 'cities' table
        }
        forecasts.append(forecast_data)

forecast_df = pd.DataFrame(forecasts)
forecast_df

,temp,feels_like,humidity_%,wind_speed,wind_gust,precipitation_%,rain_3h,snow_3h,forecast_time,city_id
0,11.60,10.41,61,2.73,5.83,0.00,0.00,0,2026-10-19 15:00:00,1
1,8.97,7.75,72,2.30,4.43,0.00,0.00,0,2026-10-19 18:00:00,1
2,8.37,7.25,78,2.05,4.12,0.00,0.00,0,2026-10-19 21:00:00,1
3,7.84,6.21,84,2.58,5.06,0.00,0.00,0,2026-10-20 00:00:00,1
4,6.91,4.97,92,2.75,5.39,0.00,0.00,0,2026-10-20 03:00:00,1
...,...,...,...,...,...,...,...,...,...,...
115,6.79,3.28,80,5.72,12.03,0.00,0.00,0,2026-10-24 00:00:00,3
116,6.06,2.63,77,5.07,10.38,0.00,0.00,0,2026-10-24 03:00:00,3
117,5.53,2.43,74,4.15,8.27,0.00,0.00,0,2026-10-24 06:00:00,3
118,9.54,7.54,56,3.79,8.74,0.00,0.00,0,2026-10-24 09:00:00,3
119,6.80,6.80,84,0.90,4.12,0.81,3.81,0,2026-10-24 12:00:00,3

In [29]:
# useful for writing the SQL table definition
forecast_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   temp             120 non-null    float64
 1   feels_like       120 non-null    float64
 2   humidity_%       120 non-null    int64
 3   wind_speed       120 non-null    float64
 4   wind_gust        120 non-null    float64
 5   precipitation_%  120 non-null    float64
 6   rain_3h          120 non-null    float64
 7   snow_3h          120 non-null    int64
 8   forecast_time    120 non-null    str
 9   city_id          120 non-null    int64
dtypes: float64(6), int64(3), str(1)
memory usage: 9.5 KB

In [30]:
# forecast_df.to_sql(
#     "forecasts",
#     con=connection_string,
#     if_exists="append",
#     index=False
# )